import { parseArgs } from "../args.ts";
import type { Context } from "../context.ts";
import { fail } from "../errors.ts";

/**
 * Shell completion.
 *
 * The interesting part is that it completes your *own* rules: `slopenv rm <TAB>`
 * offers the variables you have actually registered, and the directory argument
 * offers the directories they are registered for. Those come from
 * `slopenv list --names` and `--dirs`, which are plain line-per-item output and
 * never read the keychain, so they are cheap enough to sit behind a TAB press.
 *
 * Both scripts are written to be `eval`d rather than dropped in `$fpath`, which
 * is what the shell hook does with them, so one line in ~/.zshrc gets you both.
 */

const COMMANDS: ReadonlyArray<readonly [string, string]> = [
  ["set-secret", "store a secret in the keychain and add a rule"],
  ["set", "add a plain-text rule for a non-secret value"],
  ["rm", "remove a rule, and its keychain entry if it had one"],
  ["list", "show every rule"],
  ["status", "show what applies in a directory and which rule wins"],
  ["doctor", "check the hook, the rules file and the keychain"],
  ["edit", "open the rules file in \\$EDITOR"],
  ["hook", "print the shell hook"],
  ["completions", "print the shell completion script"],
  ["export", "internal: print the export/unset statements to eval"],
];

export function zshCompletions(): string {
  const described = COMMANDS.map(([name, description]) => `    '${name}:${description}'`).join("\n");

  return `# slopenv — zsh completion. Generated by \`slopenv completions zsh\`.
# It is included in \`slopenv hook zsh\`, so you usually do not need this directly.

_slopenv_names() {
  local -a names
  names=(\${(f)"\$(command slopenv list --names 2>/dev/null)"})
  (( \${#names} )) && _describe -t slopenv-names 'registered variable' names
}

_slopenv_ruledirs() {
  local -a dirs
  dirs=(\${(f)"\$(command slopenv list --dirs 2>/dev/null)"})
  (( \${#dirs} )) && _describe -t slopenv-dirs 'rule directory' dirs
  _files -/
}

_slopenv() {
  local curcontext="\$curcontext" state line
  typeset -A opt_args

  local -a _slopenv_commands
  _slopenv_commands=(
${described}
  )

  _arguments -C \\
    '(- *)'{-h,--help}'[show usage]' \\
    '(- *)'{-v,--version}'[show the version]' \\
    '1: :->command' \\
    '*:: :->args'

  case \$state in
    command)
      _describe -t commands 'slopenv command' _slopenv_commands
      ;;
    args)
      case \$words[1] in
        set|set-secret)
          _arguments \\
            '--dir[directory the rule applies to]:directory:_slopenv_ruledirs' \\
            '--value[value to store]:value:' \\
            '--alias[human label shown by list]:alias:' \\
            '(-y --yes -f --force)'{-y,--yes,-f,--force}'[skip the credential confirmation]' \\
            '1:variable (NAME or NAME=VALUE):_slopenv_names' \\
            '2:directory:_slopenv_ruledirs'
          ;;
        rm)
          _arguments \\
            '--dir[directory the rule applies to]:directory:_slopenv_ruledirs' \\
            '1:variable:_slopenv_names' \\
            '2:directory:_slopenv_ruledirs'
          ;;
        list)
          _arguments \\
            '--json[machine-readable output, never includes secret values]' \\
            '--names[print registered variable names, one per line]' \\
            '--dirs[print rule directories, one per line]'
          ;;
        status|export)
          _arguments '1:directory:_slopenv_ruledirs'
          ;;
        hook)
          _arguments \\
            '1:shell:(zsh bash)' \\
            '--simple[no shell-side caching; call slopenv on every cd]'
          ;;
        completions)
          _arguments '1:shell:(zsh bash)'
          ;;
      esac
      ;;
  esac
}

# compdef only exists once compinit has run. Registering without it is an error,
# and an error inside an \`eval\` at shell startup is a bad way to find that out.
if (( \$+functions[compdef] )); then
  compdef _slopenv slopenv
fi
`;
}

export function bashCompletions(): string {
  const names = COMMANDS.map(([name]) => name).join(" ");

  return `# slopenv — bash completion. Generated by \`slopenv completions bash\`.
# It is included in \`slopenv hook bash\`.

_slopenv() {
  local cur prev words cword
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  local command="\${COMP_WORDS[1]}"

  if [ "\$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( \$(compgen -W "${names} --help --version" -- "\$cur") )
    return
  fi

  case "\$prev" in
    --dir)
      COMPREPLY=( \$(compgen -W "\$(command slopenv list --dirs 2>/dev/null)" -- "\$cur") )
      COMPREPLY+=( \$(compgen -d -- "\$cur") )
      return
      ;;
    --value|--alias)
      return
      ;;
  esac

  case "\$command" in
    set|set-secret|rm)
      if [ "\$COMP_CWORD" -eq 2 ]; then
        COMPREPLY=( \$(compgen -W "\$(command slopenv list --names 2>/dev/null)" -- "\$cur") )
      else
        COMPREPLY=( \$(compgen -W "\$(command slopenv list --dirs 2>/dev/null)" -- "\$cur") )
        COMPREPLY+=( \$(compgen -d -- "\$cur") )
      fi
      ;;
    list)
      COMPREPLY=( \$(compgen -W "--json --names --dirs" -- "\$cur") )
      ;;
    status|export)
      COMPREPLY=( \$(compgen -W "\$(command slopenv list --dirs 2>/dev/null)" -- "\$cur") )
      COMPREPLY+=( \$(compgen -d -- "\$cur") )
      ;;
    hook)
      COMPREPLY=( \$(compgen -W "zsh bash --simple" -- "\$cur") )
      ;;
    completions)
      COMPREPLY=( \$(compgen -W "zsh bash" -- "\$cur") )
      ;;
  esac
}

complete -F _slopenv slopenv
`;
}

export function cmdCompletions(argv: readonly string[], ctx: Context): number {
  const args = parseArgs(argv, {});
  const shell = args.positional[0];

  if (!shell) fail("usage: slopenv completions <zsh|bash>");

  switch (shell) {
    case "zsh":
      ctx.out(zshCompletions());
      return 0;
    case "bash":
      ctx.out(bashCompletions());
      return 0;
    default:
      return fail(`unsupported shell ${JSON.stringify(shell)} — expected zsh or bash`);
  }
}
