import { basename, resolve } from "node:path";
import type { Context } from "../context.ts";
import { fail } from "../errors.ts";
import { parseArgs } from "../args.ts";
import { shellQuote } from "../shell.ts";

/**
 * How the shell should invoke us. When running from a compiled binary that is
 * just `process.execPath`; when running from source under `bun` it has to be
 * `bun /path/to/cli.ts`, which keeps the hook usable during development.
 */
function invocation(): string {
  const exec = process.execPath;
  const name = basename(exec);
  if (name === "bun" || name === "bun-debug") {
    const script = process.argv[1];
    if (script) return `${shellQuote(exec)} ${shellQuote(resolve(script))}`;
  }
  return shellQuote(exec);
}

function zshHook(bin: string, rulesPath: string, simple: boolean): string {
  const header = `# slopenv — zsh hook. Generated by \`slopenv hook zsh\`.\n# Add to ~/.zshrc:  eval "$(slopenv hook zsh)"\n`;

  if (simple) {
    return `${header}
if [[ -z \${_SLOPENV_HOOK_LOADED:-} ]]; then
  _SLOPENV_HOOK_LOADED=1
  export SLOPENV_CONFIG=\${SLOPENV_CONFIG:-${shellQuote(rulesPath)}}

  _slopenv_hook() {
    emulate -L zsh
    local out
    # A non-zero exit means something went wrong; skip the eval rather than
    # risk evaluating a partial script.
    out="$(${bin} export "$PWD")" || return 0
    eval "$out"
  }

  autoload -Uz add-zsh-hook
  add-zsh-hook chpwd _slopenv_hook
  _slopenv_hook
fi
`;
  }

  return `${header}
if [[ -z \${_SLOPENV_HOOK_LOADED:-} ]]; then
  _SLOPENV_HOOK_LOADED=1
  export SLOPENV_CONFIG=\${SLOPENV_CONFIG:-${shellQuote(rulesPath)}}
  zmodload -F zsh/stat b:zstat 2>/dev/null

  # Fast path. Everything slopenv would export is a pure function of (rules file,
  # \$PWD), so if the rules file is unchanged *and* the set of rule directories
  # covering \$PWD is unchanged, nothing can have changed and we skip the fork.
  # This runs on every prompt, so it does no forking of its own: zstat is a
  # builtin and \${PWD:P} resolves symlinks in-process.
  _slopenv_hook() {
    emulate -L zsh
    local -A st
    local fp rp match d out

    # zstat takes at most one +element, hence the hash form. mtime is whole
    # seconds here and on slopenv's side; the inode is what makes this reliable,
    # since every write lands via rename onto a fresh file.
    if zstat -H st -- "$SLOPENV_CONFIG" 2>/dev/null; then
      fp="\${st[inode]}:\${st[mtime]}:\${st[size]}"
    else
      fp="0:0:0"
    fi

    rp=\${PWD:P}
    match=""
    for d in \${(f)SLOPENV_DIRS}; do
      [[ -n $d ]] || continue
      if [[ $rp == "$d" || $rp == "$d"/* ]]; then
        match+="$d"$'\\n'
      fi
    done

    if [[ -n \${SLOPENV_STATE:-} && $fp == "$SLOPENV_FP" && $match == "$SLOPENV_MATCH" ]]; then
      return 0
    fi

    out="$(${bin} export "$PWD")" || return 0
    eval "$out"
  }

  autoload -Uz add-zsh-hook
  add-zsh-hook chpwd _slopenv_hook
  add-zsh-hook precmd _slopenv_hook
  _slopenv_hook
fi
`;
}

function bashHook(bin: string, rulesPath: string): string {
  return `# slopenv — bash hook. Generated by \`slopenv hook bash\`.
# Add to ~/.bashrc:  eval "$(slopenv hook bash)"
#
# Note: bash has no chpwd, so this compares $PWD on each prompt. That means rule
# changes made in another terminal are picked up on your next cd, not your next
# prompt. zsh gets the better hook.
if [ -z "\${_SLOPENV_HOOK_LOADED:-}" ]; then
  _SLOPENV_HOOK_LOADED=1
  export SLOPENV_CONFIG="\${SLOPENV_CONFIG:-${rulesPath}}"

  _slopenv_hook() {
    if [ "$PWD" = "\${_SLOPENV_LAST_PWD:-}" ] && [ -n "\${SLOPENV_STATE:-}" ]; then
      return 0
    fi
    _SLOPENV_LAST_PWD="$PWD"
    local out
    out="$(${bin} export "$PWD")" || return 0
    eval "$out"
  }

  case ";\${PROMPT_COMMAND:-};" in
    *";_slopenv_hook;"*) ;;
    *) PROMPT_COMMAND="_slopenv_hook\${PROMPT_COMMAND:+;\$PROMPT_COMMAND}" ;;
  esac
  _slopenv_hook
fi
`;
}

export function cmdHook(argv: readonly string[], ctx: Context): number {
  const args = parseArgs(argv, { boolean: ["simple"] });
  const shell = args.positional[0];

  if (!shell) fail("usage: slopenv hook <zsh|bash> [--simple]");

  const bin = invocation();

  switch (shell) {
    case "zsh":
      ctx.out(zshHook(bin, ctx.rulesPath, args.flags.has("simple")));
      return 0;
    case "bash":
      ctx.out(bashHook(bin, ctx.rulesPath));
      return 0;
    case "fish":
      return fail(
        "no fish hook yet — fish needs a different quoting dialect in the emitter. Use zsh or bash for now.",
      );
    default:
      return fail(`unsupported shell ${JSON.stringify(shell)} — expected zsh or bash`);
  }
}
